### ISSUE TITLE
ur object should have add key "personality" with value of : "issues"

### ISSUE THREAD

**Issue by 0xjeji** [Ohmrrr/ohmrrr#2]
jia was here, ur welcome pls dont ban me

**Comment by 0xjeji** [comment]
const ohmrr = {
  name: "Omar",
  personality: "issues", 
  bio: "Programming for fun.",
  repositories: {
    owned: 12,
    contributedTo: 4
  },
  pullRequests: 7,
  codeReviews: 3,
  totalCommits: 354,
  stars: 8,
  followers: 4,
  following: 5,
  location: "California, USA",
  created: "August 19th, 2021"
}

**Comment by ohmrr** [comment]
Ur object shouldnt exist...
